# Generated by Django 4.2.2 on 2024-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='URL'),
        ),
    ]
