# Generated by Django 4.2.2 on 2024-06-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='менеджер'),
        ),
    ]
