# Generated by Django 4.2.2 on 2024-06-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
