# Generated by Django 4.2.2 on 2024-06-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'mailing', 'verbose_name_plural': 'mailing'},
        ),
    ]
