# Generated by Django 4.2.2 on 2024-06-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_slug'),
        ('mailing', '0003_alter_mailing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='message'),
        ),
    ]
