# Generated by Django 4.2.2 on 2024-06-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_slug'),
        ('mailing', '0004_mailing_slug_alter_mailing_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('try_status', models.CharField(choices=[('success', 'успешно'), ('fail', 'не успешно')], max_length=50, verbose_name='статус попытки')),
                ('server_answer', models.CharField(blank=True, max_length=250, null=True, verbose_name='ответ почтового сервера')),
                ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='контакты клиентов')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
