# Generated by Django 4.2.2 on 2024-06-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='topic_mailing',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='mailing name'),
        ),
    ]
